## Elasticsearch parameters
elasticsearch:
  fullnameOverride: elasticsearch-ha
  clusterName: "elasticsearch"
  image:
    registry: docker.io
    repository: bitnami/elasticsearch
    tag: 8.12.2-debian-12-r0
  sysctlImage:
    enabled: false
  master:
    replicaCount: 1
    heapSize: "128m"
    networkPolicy:
      enabled: false
      allowExternal: false
    resources:
      requests:
        cpu: "20m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "512Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "256Mi"
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    livenessProbe:
      enabled: true
      initialDelaySeconds: 300
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
  data:
    replicaCount: 1
    networkPolicy:
      enabled: false
      allowExternal: false
    heapSize: "128m"
    resources:
      requests:
        cpu: "20m"
        memory: "256Mi"
      limits:
        cpu: "150m"
        memory: "512Mi"
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "1Gi"
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    livenessProbe:
      enabled: true
      initialDelaySeconds: 500
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

  # This will be running internal to the Openshift cluster only, never exposed
  security:
    enabled: false
    fipsMode: false
    tls:
      restEncryption: false
      autoGenerated: false

  metrics:
    enabled: false
