apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: "{{ $.Values.appName }}-web"
  name: "permit-portal-route"
spec:
  host: "{{ .Values.route.spec.host }}"
  port:
    targetPort: 3000-tcp
  # manage certs manually for now
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: "{{ $.Values.appName }}-web"
    weight: 100
  wildcardPolicy: None
